### ISSUE TITLE
Front end - How to use page perhaps?

### ISSUE THREAD

**Issue by jhanna60** [TeamWicket/Twilio-BCP-CallTree#43]
Add a how to use page with a link from the dashboard perhaps?

**Comment by jvmazagao** [comment]
@jhanna60 can you give me a better elaboration of this issue?

**Comment by jhanna60** [comment]
Hi @jvmazagao apologies this wasnt a well thought out task as it was a last minute brain dump from a long time ago. Our idea was to have some form of 'How to' page ie perhaps an 'Information' button or something on the Dashboard to show the flow of this app and how people can setup and use an event. Think of it as a Help Me resource really.

Open to ideas.
