### ISSUE TITLE
Wizard to create events

### ISSUE THREAD

**Issue by AlessandroArosio** [TeamWicket/Twilio-BCP-CallTree#76]
Currently just now we have an entry form provided mainly by React-Admin, it would be great to have a 'wizard' component to guide us through the event setup.

For example it would explain each step and save the input and provide a breadcrumb trail so the user can go back and adjust something if they needed and finally when they get to the end they have the ability to go ahead and start the event.

Please keep any suggestions following the Material design look and feel.

**Comment by lywc20** [comment]
Hello, 
I'm interested in this task.
May I partake this task?

**Comment by TeamWicket** [comment]
Sure @lywc20 !

**Comment by lywc20** [comment]
#93 @TeamWicket
