### ISSUE TITLE
Fund dependencies

### ISSUE THREAD

**Issue by jvmazagao** [TeamWicket/Twilio-BCP-CallTree#97]
Today we have 109 vulnerabilities in our front-end,
![Screen Shot 2020-10-30 at 13 31 05](https://user-images.githubusercontent.com/22477816/97731639-2ad57600-1ab4-11eb-863f-502c0eb3d08e.png)

We need to fund theirs and evaluate if this broke our components.

**Comment by jhanna60** [comment]
Good idea
